---

- hosts: all
  become: true
  become_user: root
  # Disable gathering of facts until we're sure that python is installed
  gather_facts: False
  pre_tasks:
    - name: Install Python for Ansible's use
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""

    - setup: # Now do the `gather_facts` step

# Python should be installed at this point. Carry on usual.

- hosts: all
  roles:
    - common

- hosts: kirokus
  roles:
    - "sync-server"
    - "motion-server"
